[package]
name = "oauth2-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
oauth2 = "5.0.0-alpha.4"
serde = { version = "1.0.208", features = ["derive"] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
